### PR TITLE
feat: add styling for jsx using twind

### PR DESCRIPTION
**Pull request by kibibites**
usage:
```tsx
import { defineConfig, install } from "@twind/core";

// create a twind config
const twindConfig = defineConfig({
  presets: [presetAutoPrefix(), presetTailwind()],
});

// install the twind connfig
install(twindConfig)

// use
const app = new cheetah();

app.get('/', (c) => render(c, <h3 class="text-sm italic" id="styled">styled <code class="font-mono">h3</code> component</h3>))
  
app.serve() // your element should be styled!
```

### CODE REVIEW

**Comment by kibibites** [comment]
testing is a bit inefficient
there is probably a way to test for styling without using `DOMParser` :p
importing a big module just for testing is kind of an overkill imo

**Comment by boywithkeyboard** [comment]
@not-ivy you forgot to run `deno task check`.

**Comment by kibibites** [comment]
squash and merge please 😄

**Comment by boywithkeyboard** [comment]
@not-ivy could you please move the updated `jsx` function to the root and name the file `render.ts` & the function `render` plus leave the original test suite as is and create a separate one (`render.test.ts`) inside the test directory?

I'll then deprecate the old implementation.

**Review by boywithkeyboard — APPROVED** [review]
lgtm

**Pull request merged**
